import type { KalenderTermin, Lead } from '@/lib/types'

/** Platzhalter bis echte Supabase-Abfragen angebunden sind */
export const demoLeads: Lead[] = [
  {
    id: '1',
    kunde_id: null,
    kanal: 'website',
    status: 'neu',
    situation: 'Bad-Renovierung',
    bereiche: ['Fliesen', 'Elektro'],
    preis_min: 8000,
    preis_max: 12000,
    plz: '10115',
    zeitraum: 'Q2',
    kundentyp: 'privat',
    funnel_daten: null,
    kontakt_name: 'Anna Schmidt',
    kontakt_email: 'anna@example.com',
    kontakt_telefon: '+49 170 0000000',
    kontakt_nachricht: 'Kurzfristige Besichtigung möglich?',
    notizen: null,
    erstellt_von: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    kunde_id: null,
    kanal: 'telefon',
    status: 'kontaktiert',
    situation: 'Küche',
    bereiche: ['Sanitär'],
    preis_min: 4000,
    preis_max: 7000,
    plz: '10437',
    zeitraum: 'Sommer',
    kundentyp: 'privat',
    funnel_daten: null,
    kontakt_name: 'Ben Köhler',
    kontakt_email: 'ben@example.com',
    kontakt_telefon: null,
    kontakt_nachricht: null,
    notizen: 'Rückruf Mo 10:00',
    erstellt_von: null,
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '3',
    kunde_id: null,
    kanal: 'whatsapp',
    status: 'angebot',
    situation: 'Fenster',
    bereiche: null,
    preis_min: null,
    preis_max: null,
    plz: '12043',
    zeitraum: null,
    kundentyp: 'gewerbe',
    funnel_daten: null,
    kontakt_name: 'Cora Yilmaz',
    kontakt_email: null,
    kontakt_telefon: '+49 151 1111111',
    kontakt_nachricht: null,
    notizen: null,
    erstellt_von: null,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
]

export const demoTermineHeute: KalenderTermin[] = [
  {
    id: 't1',
    lead_id: '1',
    auftrag_id: null,
    titel: 'Besichtigung Bad',
    beschreibung: null,
    typ: 'besichtigung',
    datum: new Date().toISOString().slice(0, 10),
    uhrzeit_von: '10:00',
    uhrzeit_bis: '11:00',
    adresse: 'Berlin-Mitte',
    erledigt: false,
    created_at: new Date().toISOString(),
  },
  {
    id: 't2',
    lead_id: null,
    auftrag_id: null,
    titel: 'Abnahme Elektro',
    beschreibung: 'Steckdosen/Wohnzimmer',
    typ: 'abnahme',
    datum: new Date().toISOString().slice(0, 10),
    uhrzeit_von: '15:30',
    uhrzeit_bis: null,
    adresse: 'Neukölln',
    erledigt: false,
    created_at: new Date().toISOString(),
  },
]
