import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlertTriangle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bell,
  Briefcase,
  Building2,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  ClipboardList,
  ClipboardPen,
  Clock,
  CloudUpload,
  Copy,
  Download,
  Droplets,
  Equal,
  ExternalLink,
  Eye,
  File,
  FilePen,
  FileText,
  FileWarning,
  Files,
  Filter,
  FolderOpen,
  Folders,
  Forward,
  Globe,
  GripVertical,
  HelpCircle,
  History,
  Hourglass,
  Image,
  ImagePlus,
  Import,
  Inbox,
  Info,
  Layers2,
  LayoutDashboard,
  LayoutGrid,
  LayoutTemplate,
  Link,
  List,
  ListChecks,
  ListOrdered,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Minus,
  MoreHorizontal,
  Pencil,
  Percent,
  Phone,
  PhoneOff,
  Play,
  Plug,
  Plus,
  Receipt,
  Save,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShieldX,
  Star,
  Tag,
  Trash2,
  TrendingUp,
  Trophy,
  Type,
  Upload,
  User,
  UserX,
  Users,
  Wrench,
  X,
  XCircle,
  Kanban,
} from 'lucide-react'

/**
 * Mock-Icon-Namen (Tabler/`Icon n="…"`) → lucide-react.
 * Kein generischer Fallback — unbekannte Namen scheitern bewusst.
 */
export const ICON_MAP = {
  activity: Activity,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrows-exchange': ArrowLeftRight,
  bell: Bell,
  'brand-google': Globe,
  'brand-whatsapp': MessageCircle,
  briefcase: Briefcase,
  'briefcase-off': Briefcase,
  building: Building2,
  calculator: Calculator,
  calendar: Calendar,
  'calendar-event': CalendarDays,
  'calendar-plus': CalendarPlus,
  check: Check,
  checklist: ListChecks,
  checks: CheckCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-check-filled': CheckCircle2,
  'circle-x': XCircle,
  'clipboard-list': ClipboardList,
  clock: Clock,
  'cloud-upload': CloudUpload,
  copy: Copy,
  'database-import': Import,
  'device-floppy': Save,
  dots: MoreHorizontal,
  download: Download,
  droplet: Droplets,
  equal: Equal,
  'external-link': ExternalLink,
  eye: Eye,
  file: File,
  'file-invoice': FileText,
  'file-off': FileWarning,
  'file-pencil': FilePen,
  'file-text': FileText,
  files: Files,
  filter: Filter,
  'folder-open': FolderOpen,
  folders: Folders,
  forms: ClipboardPen,
  'grip-vertical': GripVertical,
  help: HelpCircle,
  history: History,
  hourglass: Hourglass,
  inbox: Inbox,
  'inbox-off': Inbox,
  'info-circle': Info,
  layout: LayoutTemplate,
  'layout-dashboard': LayoutDashboard,
  'layout-kanban': Kanban,
  link: Link,
  list: List,
  'list-details': List,
  'list-numbers': ListOrdered,
  'list-search': Search,
  mail: Mail,
  'mail-forward': Forward,
  'map-pin': MapPin,
  'map-pin-filled': MapPin,
  message: MessageSquare,
  messages: MessagesSquare,
  minus: Minus,
  pencil: Pencil,
  percentage: Percent,
  phone: Phone,
  'phone-off': PhoneOff,
  photo: Image,
  'photo-plus': ImagePlus,
  'player-play-filled': Play,
  plug: Plug,
  plus: Plus,
  receipt: Receipt,
  search: Search,
  send: Send,
  settings: Settings,
  'shield-check': ShieldCheck,
  'shield-x': ShieldX,
  'stack-2': Layers2,
  star: Star,
  'star-filled': Star,
  tag: Tag,
  'text-caption': Type,
  timeline: History,
  tool: Wrench,
  trash: Trash2,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  user: User,
  'user-off': UserX,
  users: Users,
  world: Globe,
  x: X,
} as const satisfies Record<string, LucideIcon>

export type MockIconName = keyof typeof ICON_MAP

export function isMockIconName(n: string): n is MockIconName {
  return Object.prototype.hasOwnProperty.call(ICON_MAP, n)
}

/** Löst einen Mock-Namen auf — wirft bei unbekanntem Namen (kein Fallback). */
export function resolveMockIcon(n: MockIconName | string): LucideIcon {
  if (!isMockIconName(n)) {
    throw new Error(`Unbekanntes Mock-Icon: "${n}"`)
  }
  return ICON_MAP[n]
}

/** Semantische Alias-Namen für CRM-Detail-Tabs (Mock-Vokabular). */
export const DETAIL_TAB_ICONS = {
  stammdaten: 'clipboard-list',
  details: 'list-details',
  uebersicht: 'layout-dashboard',
  zahlplan: 'calculator',
  finanzen: 'calculator',
  bautagebuch: 'clipboard-list',
  baustelle: 'tool',
  verlauf: 'history',
  timeline: 'history',
  aktivitaet: 'history',
  dokumente: 'files',
  notizen: 'messages',
  schritte: 'checklist',
  leistung: 'list-numbers',
  positionen: 'list-numbers',
  projekt: 'list-details',
  compliance: 'shield-check',
  organisation: 'building',
  kommunikation: 'mail',
  vorgaenge: 'folders',
  auftraege: 'briefcase',
} as const satisfies Record<string, MockIconName>

export type DetailTabIconKey = keyof typeof DETAIL_TAB_ICONS

export function resolveDetailTabIcon(key: DetailTabIconKey | string): LucideIcon {
  const name = DETAIL_TAB_ICONS[key as DetailTabIconKey]
  if (!name) {
    throw new Error(`Kein Detail-Tab-Icon für: "${key}"`)
  }
  return resolveMockIcon(name)
}
