/**
 * Toast-Texte (Erfolg/Fehler/Hinweis) — nur hier erweitern.
 * Budget ≤ 8 Wörter (docs/COPY-REGELN.md). Auto-Katalog aus Ist-Stand.
 */
export const TOAST = {
  bis_darf_nicht_vor_von_liegen: "„Bis“ darf nicht vor „Von“ liegen.",
  abgelehnt_nacharbeit_maengel: "Abgelehnt — Nacharbeit / Mängel",
  abgelehnt_neu_hochladen: "Abgelehnt — neu hochladen",
  abgelehnt_partner_kann_erneut_abschliessen: "Abgelehnt — Partner kann erneut abschließen.",
  abgelehnt_partner_kann_neu_hochladen: "Abgelehnt — Partner kann neu hochladen",
  abschlag_nur_mit_auftrag: "Abschlag nur mit Auftrag",
  abschlagsplaene_sind_nur_mit_auftrag_moeglich: "Abschlagspläne sind nur mit Auftrag möglich.",
  abschlagsrechnungen_sind_nur_mit_auftrag_moeglic: "Abschlagsrechnungen sind nur mit Auftrag möglich.",
  abschluss_rueckgaengig: "Abschluss rückgängig",
  abschlussbericht_erst_nach_signiertem_abnahmepro: "Abschlussbericht erst nach signiertem Abnahmeprotokoll möglich.",
  abschlussbericht_erstellt: "Abschlussbericht erstellt",
  als_gesendet_markiert: "Als gesendet markiert",
  als_kontaktiert_markiert: "Als kontaktiert markiert",
  aenderungsprotokoll_geoeffnet_demo: "Änderungsprotokoll geöffnet (Demo)",
  anfrage_als_verloren_markiert: "Anfrage als verloren markiert.",
  anfrage_angelegt: "Anfrage angelegt",
  anfrage_bestaetigt: "Anfrage bestätigt",
  anfrage_erfasst: "Anfrage erfasst",
  anfrage_geloescht: "Anfrage gelöscht",
  anfrage_gespeichert: "Anfrage gespeichert",
  anfrage_kopiert: "Anfrage kopiert",
  angebot_abgelehnt: "Angebot abgelehnt",
  angebot_abgelehnt_lead_geschlossen: "Angebot abgelehnt — Lead geschlossen",
  angebot_geloescht: "Angebot gelöscht",
  angelegt: "Angelegt",
  anlage_angelegt: "Anlage angelegt",
  anlage_geloescht: "Anlage gelöscht",
  anlage_gespeichert: "Anlage gespeichert",
  anlage_stillgelegt: "Anlage stillgelegt",
  ansprechpartner_geloescht: "Ansprechpartner gelöscht",
  auftrag_abgeschlossen: "Auftrag abgeschlossen",
  auftrag_erstellt: "Auftrag erstellt",
  auftrag_erstellt_bestaetigung_gesendet: "Auftrag erstellt — Bestätigung gesendet",
  auftrag_erstellt_ohne_kundenmail_ohne_hv_freigab: "Auftrag erstellt — ohne Kundenmail / ohne HV-Freigabe",
  auftrag_fehlt_fotos_koennen_nicht_hochgeladen_we: "Auftrag fehlt — Fotos können nicht hochgeladen werden.",
  auftrag_fehlt: "Auftrag fehlt.",
  auskunft_exportiert: "Auskunft exportiert",
  av_vertrag_geoeffnet_demo: "AV-Vertrag geöffnet (Demo)",
  baustopp_beendet: "Baustopp beendet",
  baustopp_gespeichert: "Baustopp gespeichert",
  bautagesbericht_gespeichert: "Bautagesbericht gespeichert",
  bauvorhaben_und_leistungsumfang_ausfuellen: "Bauvorhaben und Leistungsumfang ausfüllen.",
  beleg_hochgeladen: "Beleg hochgeladen",
  berechtigung_nicht_erteilt: "Berechtigung nicht erteilt.",
  bereits_verknuepft: "Bereits verknüpft",
  bewohner_angelegt: "Bewohner angelegt",
  bewohner_geloescht: "Bewohner gelöscht",
  bewohner_gespeichert: "Bewohner gespeichert",
  bezeichnung_erforderlich: "Bezeichnung erforderlich",
  bezeichnung_fehlt: "Bezeichnung fehlt.",
  bezeichnung_ist_erforderlich: "Bezeichnung ist erforderlich.",
  bitte_bei_allen_artikel_positionen_eine_bezeichn: "Bitte bei allen Artikel-Positionen eine Bezeichnung eintragen.",
  bitte_bei_allen_positionen_eine_bezeichnung_eint: "Bitte bei allen Positionen eine Bezeichnung eintragen.",
  bitte_beschreibung_oder_foto_hinzufuegen: "Bitte Beschreibung oder Foto hinzufügen.",
  bitte_betreff_und_nachricht_ausfuellen: "Bitte Betreff und Nachricht ausfüllen.",
  bitte_datum_waehlen: "Bitte Datum wählen.",
  bitte_den_leistungszeitraum_bis_angeben: "Bitte den Leistungszeitraum (bis) angeben.",
  bitte_die_app_zuerst_zum_home_bildschirm_hinzufu: "Bitte die App zuerst zum Home-Bildschirm hinzufügen.",
  bitte_dokument_oder_foto_auswaehlen_max_5_mb: "Bitte Dokument oder Foto auswählen (max. 5 MB).",
  bitte_dokument_oder_foto_auswaehlen: "Bitte Dokument oder Foto auswählen.",
  bitte_ein_angebots_pdf_auswaehlen: "Bitte ein Angebots-PDF auswählen.",
  bitte_ein_bild_jpeg_png_oder_webp_waehlen: "Bitte ein Bild (JPEG, PNG oder WebP) wählen",
  bitte_ein_gewerk_waehlen: "Bitte ein Gewerk wählen.",
  bitte_eine_leistung_aus_der_liste_waehlen: "Bitte eine Leistung aus der Liste wählen.",
  bitte_eine_nachricht_an_den_partner_eingeben: "Bitte eine Nachricht an den Partner eingeben.",
  bitte_einen_ablehnungsgrund_angeben: "Bitte einen Ablehnungsgrund angeben.",
  bitte_einen_ablehnungsgrund_waehlen: "Bitte einen Ablehnungsgrund wählen.",
  bitte_einen_angebotstitel_angeben: "Bitte einen Angebotstitel angeben.",
  bitte_einen_grund_auswaehlen: "Bitte einen Grund auswählen.",
  bitte_einen_titel_eingeben: "Bitte einen Titel eingeben.",
  bitte_einen_titel_fuer_das_update_angeben: "Bitte einen Titel für das Update angeben.",
  bitte_firmenname_oder_vor_nachname_angeben: "Bitte Firmenname oder Vor-/Nachname angeben.",
  bitte_gueltige_monatszahl_eingeben: "Bitte gültige Monatszahl eingeben",
  bitte_kurz_beschreiben_was_angepasst_wurde: "Bitte kurz beschreiben, was angepasst wurde.",
  bitte_mindestens_eine_ausgefuehrte_leistung_eint: "Bitte mindestens eine ausgeführte Leistung eintragen.",
  bitte_mindestens_eine_empfaenger_adresse_angeben: "Bitte mindestens eine Empfänger-Adresse angeben.",
  bitte_mindestens_eine_empfaenger_adresse_in_an_a: "Bitte mindestens eine Empfänger-Adresse in An angeben.",
  bitte_mindestens_eine_empfaenger_adresse_unter_a: "Bitte mindestens eine Empfänger-Adresse unter An angeben.",
  bitte_mindestens_eine_position_fuer_den_nachtrag: "Bitte mindestens eine Position für den Nachtrag anlegen.",
  bitte_mindestens_einen_empfaenger_angeben: "Bitte mindestens einen Empfänger angeben.",
  bitte_mindestens_einen_partner_auswaehlen: "Bitte mindestens einen Partner auswählen.",
  bitte_mitarbeiter_fuer_den_vor_ort_termin_waehle: "Bitte Mitarbeiter für den Vor-Ort-Termin wählen.",
  bitte_mitarbeiter_waehlen: "Bitte Mitarbeiter wählen.",
  bitte_nachricht_ausfuellen: "Bitte Nachricht ausfüllen.",
  bitte_notiz_eingeben: "Bitte Notiz eingeben.",
  bitte_partner_auswaehlen: "Bitte Partner auswählen.",
  bitte_partner_waehlen: "Bitte Partner wählen.",
  bitte_start_datum_angeben: "Bitte Start-Datum angeben.",
  bitte_stundensatz_angeben: "Bitte Stundensatz angeben.",
  bitte_telefonnummer_eingeben: "Bitte Telefonnummer eingeben.",
  bitte_test_e_mail_eingeben: "Bitte Test-E-Mail eingeben",
  bitte_uhrzeit_waehlen: "Bitte Uhrzeit wählen.",
  bitte_von_und_bis_datum_angeben: "Bitte Von- und Bis-Datum angeben.",
  bitte_ziel_anfrage_waehlen: "Bitte Ziel-Anfrage wählen.",
  bitte_zuerst_ein_abnahmeprotokoll_erstellen: "Bitte zuerst ein Abnahmeprotokoll erstellen.",
  buergschaft_gespeichert: "Bürgschaft gespeichert",
  datei_zu_gross_maximal_5_mb: "Datei zu groß — maximal 5 MB.",
  datei_zu_gross_max_8_mb: "Datei zu groß (max. 8 MB)",
  datenexport_gestartet_demo: "Datenexport gestartet (Demo)",
  derselbe_kunde_kann_nicht_zusammengefuehrt_werde: "Derselbe Kunde kann nicht zusammengeführt werden.",
  details_gespeichert: "Details gespeichert",
  diese_rechnung_kann_nicht_korrigiert_werden: "Diese Rechnung kann nicht korrigiert werden.",
  diese_rechnung_kann_nicht_mehr_bearbeitet_werden: "Diese Rechnung kann nicht mehr bearbeitet werden.",
  direktauftrag_angelegt: "Direktauftrag angelegt",
  dokument_angenommen: "Dokument angenommen",
  dokument_bestaetigt: "Dokument bestätigt",
  dokumentGeloescht: "Dokument gelöscht",
  dokumentHochgeladen: "Dokument hochgeladen",
  drei_kontaktversuche_vorschlag_als_verloren_mark: "Drei Kontaktversuche — Vorschlag: als verloren markieren",
  e_mail_an_kund_in_gesendet: "E-Mail an Kund:in gesendet",
  e_mail_eingeben: "E-Mail eingeben",
  emailGesendet: "E-Mail gesendet",
  e_mail_versendet: "E-Mail versendet",
  e_mail_dialog_konnte_nicht_geladen_werden: "E-Mail-Dialog konnte nicht geladen werden.",
  eigentuemer_zugeordnet: "Eigentümer zugeordnet",
  einbehalt_gespeichert: "Einbehalt gespeichert",
  einheit_angelegt: "Einheit angelegt",
  einheit_geloescht: "Einheit gelöscht",
  einheit_gespeichert: "Einheit gespeichert",
  einladungslink_erzeugt: "Einladungslink erzeugt",
  eintrag_geloescht: "Eintrag gelöscht",
  eintrag_veroeffentlicht_und_e_mail_gesendet: "Eintrag veröffentlicht und E-Mail gesendet",
  endgueltig_geloescht: "Endgültig gelöscht",
  entwurf_gespeichert: "Entwurf gespeichert",
  entwurf_pruefen: "Entwurf prüfen",
  erinnerung_gesendet: "Erinnerung gesendet",
  exportGestartet: "Export gestartet",
  fachnachweis_gespeichert: "Fachnachweis gespeichert",
  feld_deaktiviert: "Feld deaktiviert",
  firmeneinstellungen_fehlen: "Firmeneinstellungen fehlen.",
  formular_angelegt: "Formular angelegt",
  foto_aus_angebot_als_ist_bild_uebernommen: "Foto aus Angebot als Ist-Bild übernommen",
  foto_hochgeladen: "Foto hochgeladen",
  fotos_aus_angebot_uebernommen: "Fotos aus Angebot übernommen",
  freigabe_erneut_angefordert: "Freigabe erneut angefordert",
  freigabe_gespeichert: "Freigabe gespeichert",
  freigegeben: "Freigegeben",
  freigegeben_versand_optional_danach: "Freigegeben — Versand optional danach",
  frist_gespeichert: "Frist gespeichert",
  fuer_die_bestaetigungs_mail_ist_ein_mitarbeiter: "Für die Bestätigungs-Mail ist ein Mitarbeiter nötig.",
  geloescht: "Gelöscht",
  gespeichert: "Gespeichert",
  gewerk_angelegt: "Gewerk angelegt",
  gewerk_nicht_in_stammdaten: "Gewerk nicht in Stammdaten",
  gewerk_nicht_in_stammdaten_2: "Gewerk nicht in Stammdaten.",
  grund_ausfuellen: "Grund ausfüllen",
  gutschrift_erstellt: "Gutschrift erstellt",
  iban_kopiert: "IBAN kopiert",
  in_formular_uebernommen: "In Formular übernommen",
  in_zwischenablage_kopiert: "In Zwischenablage kopiert",
  ist_und_ziel_bild_erforderlich: "Ist- und Ziel-Bild erforderlich",
  ist_bild_und_prompt_erforderlich: "Ist-Bild und Prompt erforderlich",
  kein_auftrag_plan_nur_am_angebot_speicherbar: "Kein Auftrag — Plan nur am Angebot speicherbar.",
  kein_auftrag_verknuepft: "Kein Auftrag verknüpft",
  kein_detail_link_vorhanden: "Kein Detail-Link vorhanden.",
  kein_kunde_verknuepft_anfrage_kann_nicht_angeleg: "Kein Kunde verknüpft — Anfrage kann nicht angelegt werden.",
  kein_kunde_verknuepft_angebot_kann_nicht_gespeic: "Kein Kunde verknüpft — Angebot kann nicht gespeichert werden.",
  kein_kunde_verknuepft_portal_link_nicht_moeglich: "Kein Kunde verknüpft — Portal-Link nicht möglich.",
  kein_kunde_verknuepft_rechnung_nicht_moeglich: "Kein Kunde verknüpft — Rechnung nicht möglich.",
  kein_kunde_verknuepft: "Kein Kunde verknüpft.",
  kein_kunden_link_bitte_zuerst_erzeugen: "Kein Kunden-Link — bitte zuerst erzeugen.",
  kein_rechnungs_pdf_hinterlegt: "Kein Rechnungs-PDF hinterlegt.",
  kein_uebernehmbarer_entwurf_in_der_antwort: "Kein übernehmbarer Entwurf in der Antwort.",
  kein_verknuepftes_angebot: "Kein verknüpftes Angebot.",
  keine_anfrage_verknuepft: "Keine Anfrage verknüpft",
  keine_anfrage_verknuepft_2: "Keine Anfrage verknüpft.",
  keine_auftragsverknuepfung_fuer_bewertung: "Keine Auftragsverknüpfung für Bewertung.",
  keine_bild_url_erhalten: "Keine Bild-URL erhalten.",
  keine_e_mail_portal_einladung_nicht_moeglich: "Keine E-Mail — Portal-Einladung nicht möglich.",
  keine_iban_hinterlegt: "Keine IBAN hinterlegt",
  keine_kunden_e_mail_bitte_unter_versand_ergaenze: "Keine Kunden-E-Mail — bitte unter Versand ergänzen.",
  keine_projekt_fotos_im_angebot: "Keine Projekt-Fotos im Angebot",
  keine_verknuepfte_anfrage: "Keine verknüpfte Anfrage.",
  konditionen_uebernommen: "Konditionen übernommen",
  kontakt_angelegt: "Kontakt angelegt",
  kontakt_geloescht: "Kontakt gelöscht",
  kontakt_gespeichert: "Kontakt gespeichert",
  kopie_wird_vorbereitet: "Kopie wird vorbereitet …",
  kopieren_fehlgeschlagen: "Kopieren fehlgeschlagen",
  kopieren_fuer_diesen_typ_noch_nicht_verfuegbar: "Kopieren für diesen Typ noch nicht verfügbar",
  kopieren_nicht_moeglich: "Kopieren nicht möglich",
  korrektur_verworfen_kein_entwurf_gespeichert: "Korrektur verworfen — kein Entwurf gespeichert",
  korrektur_entwurf_angelegt_bitte_pruefen_und_ers: "Korrektur-Entwurf angelegt — bitte prüfen und erst dann versenden",
  korrektur_entwurf_angelegt_bitte_pruefen_und_ver: "Korrektur-Entwurf angelegt — bitte prüfen und versenden",
  kostentraeger_se_vorgeschlagen: "Kostenträger SE vorgeschlagen",
  kostentraeger_versicherung_vorgeschlagen: "Kostenträger Versicherung vorgeschlagen",
  kunde_angelegt: "Kunde angelegt",
  kunde_geloescht: "Kunde gelöscht",
  kunde_kopiert: "Kunde kopiert",
  kunden_link_bereit: "Kunden-Link bereit",
  kundenportal_link_versendet: "Kundenportal-Link versendet",
  label_erforderlich: "Label erforderlich",
  leistung_angelegt: "Leistung angelegt",
  leistung_geloescht: "Leistung gelöscht",
  leistung_gespeichert: "Leistung gespeichert",
  lieferant_ausfuellen: "Lieferant ausfüllen",
  link_in_zwischenablage: "Link in Zwischenablage",
  link_kopiert: "Link kopiert",
  links_gespeichert: "Links gespeichert",
  logo_hochgeladen: "Logo hochgeladen",
  loesch_dialog_nicht_verfuegbar: "Lösch-Dialog nicht verfügbar.",
  loeschen_rueckgaengig_gemacht: "Löschen rückgängig gemacht",
  lv_anfrage_geloescht: "LV-Anfrage gelöscht",
  mangel_aktualisiert_pdf_neu_erstellt: "Mangel aktualisiert — PDF neu erstellt",
  materialaufschlag_ungueltig: "Materialaufschlag ungültig.",
  melde_link_kopiert: "Melde-Link kopiert",
  melder_leistungsort_gespeichert: "Melder & Leistungsort gespeichert",
  metadaten_gespeichert: "Metadaten gespeichert",
  mindestens_eine_abschlagszeile_erforderlich: "Mindestens eine Abschlagszeile erforderlich.",
  mindestens_eine_artikel_position_erforderlich: "Mindestens eine Artikel-Position erforderlich.",
  mindestens_eine_leistung_dem_neuen_partner_zuwei: "Mindestens eine Leistung dem neuen Partner zuweisen.",
  mindestens_eine_leistung_fuer_die_abnahme_auswae: "Mindestens eine Leistung für die Abnahme auswählen (OK).",
  mindestens_eine_leistung_fuer_die_abnahme_auswae_2: "Mindestens eine Leistung für die Abnahme auswählen.",
  mindestens_eine_leistung_mit_bezeichnung_erforde: "Mindestens eine Leistung mit Bezeichnung erforderlich.",
  mindestens_eine_position_erforderlich: "Mindestens eine Position erforderlich.",
  mit_bestehendem_kunden_verknuepft: "Mit bestehendem Kunden verknüpft",
  nachricht_kopiert: "Nachricht kopiert",
  nachtrag_auftrag_unveraendert: "Nachtrag — Auftrag unverändert",
  nachtrag_braucht_verknuepftes_angebot_und_anfrag: "Nachtrag braucht verknüpftes Angebot und Anfrage.",
  nachtrag_genehmigt_org_freigabe_geprueft: "Nachtrag genehmigt — Org-Freigabe geprüft",
  nachtrag_gespeichert: "Nachtrag gespeichert",
  name_eingeben: "Name eingeben",
  name_ist_pflicht: "Name ist Pflicht.",
  name_und_e_mail_erforderlich: "Name und E-Mail erforderlich",
  netto_betrag_pruefen: "Netto-Betrag prüfen",
  netzwerkfehler: "Keine Verbindung – Erneut versuchen",
  nicht_gespeichert: "Nicht gespeichert",
  noch_keine_position: "Noch keine Position",
  notizGeloescht: "Notiz gelöscht",
  notiz_gespeichert: "Notiz gespeichert",
  notizHinzugefuegt: "Notiz hinzugefügt",
  notizen_gespeichert: "Notizen gespeichert",
  notmassnahme_disponiert: "Notmaßnahme disponiert",
  objekt_angelegt: "Objekt angelegt",
  objekt_geloescht: "Objekt gelöscht",
  organisationseinstellungen_gespeichert: "Organisationseinstellungen gespeichert",
  partner_angelegt: "Partner angelegt",
  partner_kopiert: "Partner kopiert",
  partner_zugewiesen: "Partner zugewiesen",
  partner_angebot_manuell_erfasst: "Partner-Angebot manuell erfasst",
  partner_ek_netto_angeben_0_oder_mehr: "Partner-EK (netto) angeben (0 € oder mehr).",
  partner_link_versendet: "Partner-Link versendet",
  partner_login_kopiert_in_whatsapp_einfuegen: "Partner-Login kopiert — in WhatsApp einfügen",
  pflichtfelder_ausfuellen: "Pflichtfelder ausfüllen",
  pflichtfelder_pruefen: "Pflichtfelder prüfen",
  plan_anpassen_100: "Plan anpassen (100 %)",
  portal_konnte_nicht_geoeffnet_werden: "Portal konnte nicht geöffnet werden.",
  portal_link_kopiert: "Portal-Link kopiert",
  position_entfernt: "Position entfernt.",
  position_hinzugefuegt: "Position hinzugefügt.",
  profil_gespeichert: "Profil gespeichert",
  projektleitung_gespeichert: "Projektleitung gespeichert",
  protokoll_geloescht: "Protokoll gelöscht",
  protokoll_gesendet: "Protokoll gesendet",
  push_aktiviert: "Push aktiviert",
  push_deaktiviert: "Push deaktiviert",
  push_ist_serverseitig_noch_nicht_konfiguriert_va: "Push ist serverseitig noch nicht konfiguriert (VAPID).",
  push_wird_von_diesem_browser_nicht_unterstuetzt: "Push wird von diesem Browser nicht unterstützt.",
  qr_code_noch_nicht_bereit: "QR-Code noch nicht bereit",
  rahmenvertrag_als_pdf_erzeugt_und_hochgeladen: "Rahmenvertrag als PDF erzeugt und hochgeladen",
  rechnung_geloescht: "Rechnung gelöscht",
  rechnung_gesendet: "Rechnung gesendet",
  rechnungsentwurf_kopiert: "Rechnungsentwurf kopiert",
  regiearbeit_geloescht: "Regiearbeit gelöscht",
  regiebericht_pdf_erstellt: "Regiebericht-PDF erstellt",
  statusAktualisiert: "Status aktualisiert",
  status_auf_neu_gesetzt: "Status auf Neu gesetzt",
  storno_angelegt_korrektur_gespeichert_noch_nicht: "Storno angelegt — Korrektur gespeichert (noch nicht versendet)",
  team_gespeichert: "Team gespeichert",
  telefon_ist_pflicht: "Telefon ist Pflicht.",
  termin_geloescht: "Termin gelöscht",
  termin_gespeichert: "Termin gespeichert",
  termin_gespeichert_2: "Termin gespeichert.",
  termin_rueckgaengig: "Termin rückgängig",
  test_banner_gesendet: "Test-Banner gesendet",
  test_mail_gesendet: "Test-Mail gesendet",
  titel_fehlt: "Titel fehlt.",
  titel_text_oder_foto_angeben: "Titel, Text oder Foto angeben.",
  to_do_geloescht: "To-do gelöscht",
  transaktionsdaten_wurden_geloescht: "Transaktionsdaten wurden gelöscht.",
  um_12_monate_zurueckgestellt: "Um 12 Monate zurückgestellt",
  unterlage_gespeichert: "Unterlage gespeichert",
  upload_fehlgeschlagen: "Upload fehlgeschlagen",
  verarbeitet: "Verarbeitet",
  vertrag_als_pdf_erzeugt_und_hochgeladen: "Vertrag als PDF erzeugt und hochgeladen",
  vertrag_erzeugt: "Vertrag erzeugt",
  visualisierung_ins_angebot_uebernommen: "Visualisierung ins Angebot übernommen",
  vk_netto_ist_erforderlich: "VK netto ist erforderlich.",
  vorlage_geloescht: "Vorlage gelöscht",
  vorlage_gespeichert: "Vorlage gespeichert",
  vorschau_geoeffnet: "Vorschau geöffnet",
  wieder_als_versendet: "Wieder als versendet",
  wieder_auf_offen_gesetzt: "Wieder auf offen gesetzt",
  wochenbericht_angelegt: "Wochenbericht angelegt",
  wochenbericht_gespeichert: "Wochenbericht gespeichert",
  wochenbericht_pdf_erstellt: "Wochenbericht-PDF erstellt",
  wunschtext_erstellt_bitte_pruefen: "Wunschtext erstellt — bitte prüfen",
  zahlungsziel_aktualisiert: "Zahlungsziel aktualisiert",
  zuerst_einen_nachunternehmervertrag_mit_pdf_anle: "Zuerst einen Nachunternehmervertrag mit PDF anlegen.",
  zuordnung_entfernt: "Zuordnung entfernt",
  zusammengefuehrt_duplikat_bleibt_sichtbar: "Zusammengeführt — Duplikat bleibt sichtbar",
} as const

export type ToastKey = keyof typeof TOAST
